rwildcard = $(foreach d,$(wildcard $(1:=/*)),$(call rwildcard,$d,$2) $(filter $(subst *,%,$2),$d))

CFLAGS :=	-Isrc \
			-ffreestanding \
			-fno-rtti \
			-fno-builtin \
			-nostdlib \
			-g \
			-O2 \
			-m64 \
			-march=x86-64 \
			-mno-red-zone \
			-fno-exceptions \
			-masm=intel

LDFLAGS := 	-nostdlib \
			-z max-page-size=0x1000 \
			-Bsymbolic \
			-static

SRCDIR = src
OBJDIR = obj