rwildcard = $(foreach d,$(wildcard $(1:=/*)),$(call rwildcard,$d,$2) $(filter $(subst *,%,$2),$d))

CC = clang-14
LD = ld.lld-14
AS = nasm

CFLAGS :=	-Isrc \
			-ffreestanding \
			-fno-rtti \
			-fno-builtin \
			-nostdlib \
			-mgeneral-regs-only \
			-Wall \
			-g \
			-O2 \
			-m64 \
			-march=x86-64 \
			-mno-red-zone \
			-fno-exceptions 

ASMFLAGS := -f elf64

LDFLAGS := 	-nostdlib \
			-z max-page-size=0x1000 \
			-Bsymbolic \
			-static

SRCDIR = src
OBJDIR = obj
BINDIR = ../../bin

CFILES := $(call rwildcard, $(SRCDIR), *.c)
ASMFILES := $(call rwildcard, $(SRCDIR), *.asm)

OBJS := $(patsubst $(SRCDIR)/%.c, $(OBJDIR)/%.o, $(CFILES))
OBJS += $(patsubst $(SRCDIR)/%.asm, $(OBJDIR)/%_asm.o, $(ASMFILES))